@api = http://localhost:4000
GET {{api}}/proyects

###
GET {{api}}/proyects/2

###
GET {{api}}/proyects/count

###
POST {{api}}/proyects
Content-Type: application/json

{
    "name": "TEST POST 3",
    "startDate": "2023-03-19",
    "finishDate": "2023-06-20",
    "price": 4000000
}

###
DELETE {{api}}/proyects/6

###
PUT {{api}}/proyects/1
Content-Type: application/json

{
    "name": "PRIMER PROYECTO PRUEBA PUT",
    "startDate": "2023-03-19",
    "finishDate": "2023-06-20",
    "price": 4350000
}

#========================================| ITEMS |===========================================================

###
GET {{api}}/items/2

###
GET {{api}}/items/desc/2

###
POST {{api}}/items
Content-Type: application/json

{
    "name": "ITEMS POST",
    "unitPrice": 1000,
    "quantity": 2,
    "totalPrice": 2000,
    "proyectId": 2,
    "purchaseDate": "2023/03/27"
}

###
PUT {{api}}/items/8
Content-Type: application/json

{
    "name": "ITEMS POST MODIFIED",
    "unitPrice": 1000,
    "quantity": 2,
    "totalPrice": 2000,
    "proyectId": 2,
    "purchaseDate": "2023/03/27"
}

###
DELETE {{api}}/items/10